### ISSUE TITLE
Cherry pick "branch" issues

### ISSUE THREAD

**Issue by luca020400** [jruesga/rview#2] opened 2016-10-11 21:32 UTC
1) When the list view load there is only one item, if you open it again the list fill properly
2) The list isn't scrollable
See attachment
![screenshot_20161011-232818](https://cloud.githubusercontent.com/assets/3950785/19289387/d40c62bc-900a-11e6-9249-a54282f1f508.png)

**Comment by jruesga** [comment] 2016-10-11 21:45
Uhm, i will try to reproduce it (in my first test the list is complete filled). About 2, it's by design. It restricted to a max of 5 items (so it will not show all the list), because otherwise the list will expand behing the keyboard (which is not useful anyway). I will try to find a better way of display the list. Thx for the report Luca.

**Comment by jruesga** [comment] 2016-10-14 19:13
Fixed with edb7a5c812dc489742fc3bb5b7ea1a1718adc701

**Closed by jruesga** 2016-10-14 19:13 UTC
