### ISSUE TITLE
Crash on opening existing change

### ISSUE THREAD

**Issue by vlotorev** [jruesga/rview#68] opened 2018-03-08 13:16 UTC
I browse changes on Incoming tab and app crashes constantly while tapping specific change.
Backtrace is in attachments. I don't know how to get text backtrace easily, so screen shot attached, text is not copyable in this window.

![img_20180308_162300](https://user-images.githubusercontent.com/5903498/37153258-264abda0-22ed-11e8-9f73-eabd6a3306d1.png)

**Comment by jruesga** [comment] 2018-03-08 13:35
@vlotorev 7e62848a1d3e8b82fa075d1bc4f0bab5993dbd7d should prevent the crash, but will not linkify it. If the repo is public could you pass me the link to the crashing link? Otherwise, could you open the crashing link in a web browser and post here the url links you found in the new change? Some of the url links in the destination click link has some link that made the app to crash when tries to linkify it. Thx.

**Comment by vlotorev** [comment] 2018-03-08 18:00
My gerrit is private.

Commit message and comments contain following links:
* https://myserver.com/gerrit/#/c/6955/
* https://www.debian.org/doc/manuals/maint-guide/index.en.html
https://mycompany.atlassian.net/browse/CAPRISW-894


And gitweb urls:
* https://myserver.com/gerrit/gitweb?p=dist%2Fdebian.git;a=commit;h=409cdad0872d45b42fc46f4eed97a44ac1459ab9
* https://myserver.com/gerrit/gitweb?p=dist%2Fdebian.git;a=commit;h=409cdad0872d45b42fc46f4eed97a44ac1459ab

**Comment by jruesga** [comment] 2018-03-08 23:15
Great, thanks. I will try to reproduce the crash.

**Comment by jruesga** [comment] 2018-03-08 23:40
Uhm, it seems the problem is in one of the regexp of the comment links configured by your system administrator. With the common regexp comment links, i'm not be able to reproduce the crash.

Could you provided the comment links defined for the change that is crashing (the one that open the link)? The commentlinks are defined by project. For example for lineageos and the project LineageOS/android_build, the url https://**review.lineageos.org**/projects/**LineageOS%2Fandroid_build**/config returns a json with
...
    "commentlinks": {
        "cve": {
            "match": "\\b(CVE\\-\\d{4}\\-\\d+)\\b",
            "link": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=$1"
        }
    }
...

I need the regexp and links associated to the project, just replace the server name and the project (be sure to use url encode the project name).

I'm sure one of the regexps is causing the app to crash in someway when the app tried to linkify a url.

Thanks in advance.

**Comment by jruesga** [comment] 2018-03-09 00:34
@vlotorev could you test with this version (https://cloud.ruesga.com/f/5c6c23b5f9/)? Instead of crash, it will send to crashlytics the information about was wrong with the linkify of the url of the change (the linkifyed text, the pattern and the link). Thx in advance.

**Comment by vlotorev** [comment] 2018-03-09 11:18
@jruesga I installed the app and it doesn't crash. Comment link is not highlighted as link, just text. Will it send crashlytics silently on visiting the change?

I'll contact my server admin for comment link regexp (it's not possible to get regexp from client side, right?). Comment link regexp did change recently.

**Comment by jruesga** [comment] 2018-03-09 11:30
Yes, it will silently send to crashlytics the link information (the next time the app is open if i recall correclty. stop the app and open it again to force the upload). 


It's possible to get the links using the REST API. For example the link https://review.lineageos.org/projects/LineageOS%2Fandroid_frameworks_base/config returns a json document that have the commentlinks for the project LineageOS/android_frameworks_base in the form:

    "commentlinks": {
        "cve": {
            "match": "\\b(CVE\\-\\d{4}\\-\\d+)\\b",
            "link": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=$1"
        }
    }

You need to know which project the change belongs to and type the url on a browser

https://_**<server>**_/projects/**_<project>_**/config

Be sure you url encode the project name.

**Comment by jruesga** [comment] 2018-03-09 13:54
@vlotorev i got the crash information in crashlytics. i will try to analyze them and fix the problem. thx so much.

**Comment by jruesga** [comment] 2018-03-09 18:45
fixed in 2e74f14a325959850dc30a3323e58a694f424f3a

@vlotorev thanks for reporting the bug :)

**Closed by jruesga** 2018-03-09 18:45 UTC
Labels: bug
